# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "aegis-import"
#   createdAt: seconds:1786634392  nanos:864190336
#   expiresAt: seconds:1818170400
#   id:        4f910f79-ba49-4455-b4e8-0fe344520772
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2026-08-13T15:19:52.864190336Z"
    init-bundle.stackrox.io/expires-at: "2027-08-13T15:20:00Z"
    init-bundle.stackrox.io/id: 4f910f79-ba49-4455-b4e8-0fe344520772
    init-bundle.stackrox.io/name: aegis-import
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUJh+88tsxGk6/yE/bvHAsvn5kKoQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MB4XDTI2MDgxMzE1MDgwMFoXDTMxMDgx
    MjE1MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEu2OyUfuljgfwkCSJ/2GpTZMbZmggv6cvvtE944bk8WsQGRnL
    W+/YstRriPBM4qg4qMynP4FWCqAsTimp4vQJCKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLPy3iP9Nf8gL8oAS7Mmo5EPtcdL
    MAoGCCqGSM49BAMCA0kAMEYCIQCIojx1ymXodymTQYQFvUGNbixlQbQIyknR78bK
    g8VLVAIhALAy3xCFWNJkJYRX8QyUr8PoOydcxa7N52XsnGY6VDGj
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICszCCAlqgAwIBAgIJAPvuxSnJzQh3MAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTODE5OTcz
    Nzk5MzA0NTY0OTYzNjAeFw0yNjA4MTMxNDIwMDBaFw0yNzA4MTMxNTIwMDBaMIGm
    MS0wKwYDVQQKEyQ0ZjkxMGY3OS1iYTQ5LTQ0NTUtYjRlOC0wZmUzNDQ1MjA3NzIx
    FzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0wOwYDVQQDDDRTRU5TT1JfU0VSVklD
    RTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQF
    ExQxODE1MzY2MzkzMTI0NzAzNjUzNTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
    BOXPyJXoSakJepaAzW8uifYw5FjUhWA0BA/ve3yZL9Vc7ITjln7fAPhLpAdoNUfy
    J4MVKld8dYFvC8YGkuzyZGyjgc4wgcswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRn
    LxfRSql4iz4s7W5D0ovbMa8FJDAfBgNVHSMEGDAWgBSz8t4j/TX/IC/KAEuzJqOR
    D7XHSzBMBgNVHREERTBDgg9zZW5zb3Iuc3RhY2tyb3iCE3NlbnNvci5zdGFja3Jv
    eC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNH
    ADBEAiAvI0t0PWbBDPgj51d74bOZGYgRI5/0A8cNcbAHXVrGFQIgLHqHq30nzfcR
    xOtSDAzn3DbTMETHLq5UqSTwkyYP2XY=
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEINmJ157ecJ0zURHNzc6fMi1YV7kb1JjLeKD/s+fG8ZJvoAoGCCqGSM49
    AwEHoUQDQgAE5c/IlehJqQl6loDNby6J9jDkWNSFYDQED+97fJkv1VzshOOWft8A
    +EukB2g1R/IngxUqV3x1gW8LxgaS7PJkbA==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2026-08-13T15:19:52.864190336Z"
    init-bundle.stackrox.io/expires-at: "2027-08-13T15:20:00Z"
    init-bundle.stackrox.io/id: 4f910f79-ba49-4455-b4e8-0fe344520772
    init-bundle.stackrox.io/name: aegis-import
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwzCCAmmgAwIBAgIJAI9xZ+vDqr+YMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTODE5OTcz
    Nzk5MzA0NTY0OTYzNjAeFw0yNjA4MTMxNDIwMDBaFw0yNzA4MTMxNTIwMDBaMIG8
    MS0wKwYDVQQKEyQ0ZjkxMGY3OS1iYTQ5LTQ0NTUtYjRlOC0wZmUzNDQ1MjA3NzIx
    IjAgBgNVBAsMGUFETUlTU0lPTl9DT05UUk9MX1NFUlZJQ0UxSDBGBgNVBAMMP0FE
    TUlTU0lPTl9DT05UUk9MX1NFUlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAw
    LTAwMDAwMDAwMDAwMDEdMBsGA1UEBRMUMTAzMzYxNTY4ODIwODk3MjE3NTIwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAARDpWnGovcSamz8swvaaHWq2p8QWM9tpbnE
    fqba/6DelHA9ROzobqNPbfleye8Gkb5EWICZDxAL+rtDI12Pwtz8o4HHMIHEMA4G
    A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYD
    VR0TAQH/BAIwADAdBgNVHQ4EFgQUnIC75y4wVeWuJBbDtolzntAqwwYwHwYDVR0j
    BBgwFoAUs/LeI/01/yAvygBLsyajkQ+1x0swRQYDVR0RBD4wPIIaYWRtaXNzaW9u
    LWNvbnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2
    YzAKBggqhkjOPQQDAgNIADBFAiEAwD4+txZh14Lql2B/yVinb+jXca8tAHYXFTMo
    aRpfyYICIChmEMkMqK3PDK1M3oPngEE+uxJvyTXm66amzVFqh8aL
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIGvKXr32PMIMaEzjon/Y3fETp0NCeu4oWRrRSj7C4RlOoAoGCCqGSM49
    AwEHoUQDQgAEQ6VpxqL3Emps/LML2mh1qtqfEFjPbaW5xH6m2v+g3pRwPUTs6G6j
    T235XsnvBpG+RFiAmQ8QC/q7QyNdj8Lc/A==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUJh+88tsxGk6/yE/bvHAsvn5kKoQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MB4XDTI2MDgxMzE1MDgwMFoXDTMxMDgx
    MjE1MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEu2OyUfuljgfwkCSJ/2GpTZMbZmggv6cvvtE944bk8WsQGRnL
    W+/YstRriPBM4qg4qMynP4FWCqAsTimp4vQJCKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLPy3iP9Nf8gL8oAS7Mmo5EPtcdL
    MAoGCCqGSM49BAMCA0kAMEYCIQCIojx1ymXodymTQYQFvUGNbixlQbQIyknR78bK
    g8VLVAIhALAy3xCFWNJkJYRX8QyUr8PoOydcxa7N52XsnGY6VDGj
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2026-08-13T15:19:52.864190336Z"
    init-bundle.stackrox.io/expires-at: "2027-08-13T15:20:00Z"
    init-bundle.stackrox.io/id: 4f910f79-ba49-4455-b4e8-0fe344520772
    init-bundle.stackrox.io/name: aegis-import
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0zCCAXigAwIBAgIUJh+88tsxGk6/yE/bvHAsvn5kKoQwCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MB4XDTI2MDgxMzE1MDgwMFoXDTMxMDgx
    MjE1MDgwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExM4MTk5NzM3OTkzMDQ1NjQ5NjM2MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEu2OyUfuljgfwkCSJ/2GpTZMbZmggv6cvvtE944bk8WsQGRnL
    W+/YstRriPBM4qg4qMynP4FWCqAsTimp4vQJCKNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLPy3iP9Nf8gL8oAS7Mmo5EPtcdL
    MAoGCCqGSM49BAMCA0kAMEYCIQCIojx1ymXodymTQYQFvUGNbixlQbQIyknR78bK
    g8VLVAIhALAy3xCFWNJkJYRX8QyUr8PoOydcxa7N52XsnGY6VDGj
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICojCCAkegAwIBAgIIdrOxhIclr3owCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExM4MTk5NzM3
    OTkzMDQ1NjQ5NjM2MB4XDTI2MDgxMzE0MjAwMFoXDTI3MDgxMzE1MjAwMFowgasx
    LTArBgNVBAoTJDRmOTEwZjc5LWJhNDktNDQ1NS1iNGU4LTBmZTM0NDUyMDc3MjEa
    MBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0UxQDA+BgNVBAMMN0NPTExFQ1RPUl9T
    RVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAa
    BgNVBAUTEzg1NTMzNzUzMDAwNjc4OTcyMTAwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAAQKEhTr1zmKH4qAx/cT1UeVU9XVhZvpaSC+v4t4nEwYBHauPOrwgYEQbneC
    bwY/dipUIvf1qaWBfHLPrehzAM82o4G3MIG0MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUmoSdL6J6fLZcSdZGN+Ol4+rfH+YwHwYDVR0jBBgwFoAUs/LeI/01/yAvygBL
    syajkQ+1x0swNQYDVR0RBC4wLIISY29sbGVjdG9yLnN0YWNrcm94ghZjb2xsZWN0
    b3Iuc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0kAMEYCIQC0F+Q+u4m+AdT7rT4s
    KqfEzJhQQAyB94Pxn21g2540SQIhAKegE97nZ49qF6IjKVgZ5OpIlErbuGNIhcK0
    XrBVNgOp
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEICD+zsasAj4+wTBXw+b68wU/Zul3XF2/qPNAmoCeEuhjoAoGCCqGSM49
    AwEHoUQDQgAEChIU69c5ih+KgMf3E9VHlVPV1YWb6Wkgvr+LeJxMGAR2rjzq8IGB
    EG53gm8GP3YqVCL39amlgXxyz63ocwDPNg==
    -----END EC PRIVATE KEY-----
